### ISSUE TITLE
installer: switch to bsdinstall to bring compatibility with Hyper-V Gen2

### ISSUE THREAD

**Issue by Schroeffu** [opnsense/installer#1]
The installer does freeze at the step "Select Task: Guided installation, Manual installation, Import configuration, Reset password, Reboot, Exit". 

Version: OPNsense-18.7-OpenSSL-dvd-amd64.iso
Happens on: Hyper-V
Hyper-V VM: Generation 2, Secure Boot disabled

Screenshot: https://imgur.com/a/rSNq4qz

I have already tried the idea from https://forum.opnsense.org/index.php?topic=4470.msg17105#msg17105 to add set kern.vty="vt" and set console="efi" while booting - still freezing.  I also tried set kern.vty=sc but the its not booting anymore with exactly the same issue like here screenshoted: https://github.com/opnsense/core/issues/2254#issuecomment-382223999

I'am opening an issue here, because i really want to compare pfsense <> opnsense. pfsense was install-able on the very same hyper-v host without any issue, so, something is different to opnsense causing the issue. Sorry, there are no logs, its just freezing.

See also https://github.com/opnsense/core/issues/2254#issuecomment-372104272 , according to the comments there after closing the issue, other poeple are affected too.

**Comment by Schroeffu** [comment]
> CTRL+C should work again on 19.1.4 -- images will be available next week. Don't expect miracles just yet.

Thank you very much. Where will those images be download able? Official mirror list (can only find 19.1 from january 2019) or somewhere seperately?

**Comment by fichtner** [comment]
There will be an announcement when 19.1.4 images are out, hopefully on Friday. Still a bit of work to do. :)

**Comment by Schroeffu** [comment]
Yey, 19.1.4 images are out, I could install OpnSense 19.1.4 on Hyper-V Gen2 again with the workaround, re-login after `CRTL+C` when installer is freezing. thanks so far.

**Comment by kevin-j-morse** [comment]
Any progress on getting this fixed? At the very least it would be good to add a warning for Hyper-V users somewhere (maybe docs?) so they don't give up and switch to another distro.

**Comment by martingruening** [comment]
BTW the same happens on VMware ESXi 6.7 U1, Ctrl-C helps to restart the install

**Comment by MysticRyuujin** [comment]
So, I'm still getting this issue under Hyper-V as well, but CTRL+C does nothing. Using the `20.1` iso...

**Comment by liv3010m** [comment]
I had the exact same symptoms when trying to install OPNsense 20.1 over Bhyve on SmartOS, the Ctrl+C trick worked as advised.

**Comment by ntinti** [comment]
Same here with bhyve and opnsense 20.1 on FreeBSD 12.1

**Comment by fichtner** [comment]
Version 0.4 works fine now. Adding more polish as testing progresses, but no reason to keep this open.

**Comment by backerman** [comment]
Still seems to be an issue when installing on XCP-ng in UEFI mode - ctrl-C, re-login workaround works. (Which has to be done at guided/manual choice and swap partition confirmation.)

**Comment by fichtner** [comment]
@backerman the installer was replaced in 21.1.5 and this issue was fixed. You cannot, however, use the new installer before a new image is released (21.7 is the next one).
