### ISSUE TITLE
Scandinavian characters not inserted into password field

### ISSUE THREAD

**Issue by Ricky-Tigg** [opnsense/installer#5]
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
Scandinavian characters (_ä, ö, ..._) are not inserted into password field.

**To Reproduce**
1. To be set in QEMU/KVM for machine file in _qcow2_ format: **OS model:** FreeBSD 12.2; **Chipset:** i440FX; **Firmware:** UEFI x86_64.
2. In OPNsense: Log in as user _installer_ with password _opnsense_. Installation process:
_Ok, let’s go_ | _Change keymap (default)_ | _fi.kdb_ | _Acccept these settings_ | _Guided Installation_ | _vtbd0_ | _GPT/UEFI mode_ | Accept suggested swap partition size (4096 MiB) | Set password for _root_ using Scandinavian characters | _Reboot_.

**Expected behavior**
Scandinavian characters to be inserted into password field and recognised.

**Environment**
OPNsense-21.1-OpenSSL-dvd-amd64

**Comment by fichtner** [comment]
@Ricky-Tigg I just finished the rewrite of the installer, but haven't added a convenient password change dialog yet. If you want I can provide a test image when it's ready in a few days, although I think that UEFI support is a lot better in this new one...

**Comment by Ricky-Tigg** [comment]
Hello! A _test image_; that's an idea, a good one.

**Comment by fichtner** [comment]
From reading up on dialog(1) it might be that UEFI is sending UTF-8 characters instead of the ASCII ones fron the keymap. In that case we won't have it fixed that easily, but let's see what the new image is saying...


Cheers,
Franco

**Comment by Ricky-Tigg** [comment]
I use to run VMs with qcow2 format on virt-manager. While _keymap_ setting was still part of its UI, and when my keyboard was not recognized there,, setting the proper _keymap_ choice matching the keyboard in use, has never been applied successfully once. Default keyboard applied was then _en_US_. Reference: [Red Hat Bugzilla – Bug 1818804](https://bugzilla.redhat.com/show_bug.cgi?id=1818804). 

XML file:
```
  <os>
    <type arch="x86_64" machine="pc-i440fx-5.2">hvm</type>
    <loader readonly="yes" type="pflash">/usr/share/edk2/ovmf/OVMF_CODE.fd</loader>
    <boot dev="hd"/>
  </os>
(...)
<channel type="spicevmc">
  <target type="virtio" name="com.redhat.spice.0"/>
</channel>
```

**Comment by fichtner** [comment]
@Ricky-Tigg @fraenki you can find the latest work in progress image here for testing https://pkg.opnsense.org/FreeBSD:12:amd64/snapshots/misc/OPNsense-devel-202104161037-LibreSSL-dvd-amd64.iso.bz2

All feedback appreciated as time permits. Thanks!

**Comment by Ricky-Tigg** [comment]
- First starting

_Picture 1_
![OPNsense-devel-202104161037](https://user-images.githubusercontent.com/26058215/115013250-78566b80-9eb9-11eb-9bd2-f6518683103b.png)

- Resetting the VM | Second start; Press continuously <kbd>esc</kbd> while restarting.

_Picture 2_
![OPNsense-devel-202104161037_UI](https://user-images.githubusercontent.com/26058215/115013628-f61a7700-9eb9-11eb-8130-30fb9a274896.png)

Once there, no opportunity to enter character  into field, then test cannot be achieved. Selecting _Continue_ in UI invariably leads to the state illustrated in _Picture 1_. '`virt-manager --debug`' output available on demand

**Comment by fichtner** [comment]
Huh, none of this is part of our distribution?

**Comment by fraenki** [comment]
@Ricky-Tigg Looks like the VM was unable to boot from the image. Excuse me for asking silly questions: did you uncompress the .bz2 image?

**Comment by fraenki** [comment]
@fichtner The image booted just fine for me (on oVirt). However, when trying to setup a mirrored ZFS pool and starting the installation, it seems to stall:

![noprogress](https://user-images.githubusercontent.com/909706/115021818-c620a300-9ebc-11eb-8ce1-fb25b2f280a4.png)

Not sure if it's too early to test ZFS on the new installer.

**Comment by fraenki** [comment]
Ah, looking at `/var/log/installer.log` these are the last messages:

![instlog](https://user-images.githubusercontent.com/909706/115022121-3c250a00-9ebd-11eb-90a1-59213a76e4b9.png)

Looks like it started copying files, although the progress bar did not indicate this.
The last message looks like a user-interactive question to me, maybe this one is not handled and thus it gets stuck?

**Comment by Ricky-Tigg** [comment]
I must have been in such a hurry; I omitted indeed to uncompress the .bz2 image. I even kept blind to the text "_.bz2_" while reading it. The installation process freezes at that line:

`Trying to mount root from cd9660:/dev/iso9660/OPNSENSE_INSTALL [ro]...`

**Comment by Ricky-Tigg** [comment]
That frozen state at this line might also be encountered with stable Opnsense releases. Users have to be persistent; after a serial of resetting operations, at last it might pass over that operation that froze and lead to the login state.

Observations (Keys pressed are not a combination of ASCII-Codes and Finnish specific characters): 

- **ASCII-Codes** | Behave as expected
  - Short-pressed key converted into the insertion of its equivalent character;
  - Short-pressing key <kbd>←</kbd> deletes the character without breaking the left-sided bar composing the frame of the field.

- **Finnish specific characters** (<kbd>ä</kbd>, <kbd>ö</kbd>, <kbd>å</kbd>)
  - Short-pressed key not converted into the insertion of its equivalent character; the field remains blank;
  - Once the previous operation has been accomplished, short-pressing <kbd>←</kbd> does break the left-sided bar composing the frame of the field, indicating then that a character had been inserted and had not been made visible. Illustration when <kbd>ä</kbd>, <kbd>ö</kbd>, <kbd>å</kbd> have been pressed each once, then <kbd>←</kbd> pressed till there is nothing left to delete.
  - ![deleted_scandinavian_characters](https://user-images.githubusercontent.com/26058215/115040812-7f41a600-9eda-11eb-9344-1e36bdf5bc0d.png)
  - Long-pressing – 2–3 seconds – <kbd>ä</kbd> does insert invisible character(s) followed by a serial composed of its equivalent characters, exactly as long as follows.
  - ![deleted_scandinavian_characters_long_pressure](https://user-images.githubusercontent.com/26058215/115042974-a7ca9f80-9edc-11eb-993c-7afc0e1a5055.png)
  - Short-pressing <kbd>←</kbd> does not delete characters;
  - Long-pressing – 2–3 seconds – <kbd>←</kbd> does delete characters, still breaking the left-sided bar composing the frame of the field when kept pressed,

**Comment by fichtner** [comment]
@fraenki thanks for testing! I added some command line options for cpdup to ignore questions although I hope these files are not vital to ZFS whatever seems to be happening there (someone writes to that new disk immediately...). Maybe we should not be overwriting this file anyway? I haven't looked at mirrored pools yet but single striped ZFS seemed to work fine.

@Ricky-Tigg ok, thanks, I can try to find a reference for this behaviour and test in my Fusion UEFI environment. If it is a KVM oddity it's going to be harder to solve I think.


Cheers,
Franco

**Comment by fraenki** [comment]
@fichtner Indeed, the zpool.cache file should not be overwritten, it contains pool config and state information. I'll happily test the next installer image. I've always wanted to switch from gmirror to a mirrored ZFS pool, glad to see this is happening. :heart:

**Comment by fichtner** [comment]
@fraenki Ok, in that case I think -o should simply avoid touching on the file (which shouldn’t exist in the installers own disk and thus cpdup wants to remove). :)

Do you have experience with ZFS on UEFI?

**Comment by fraenki** [comment]
@fichtner I could switch my VM to UEFI mode for the next test, but I wouldn't claim to have valueable UEFI experience.

**Comment by Ricky-Tigg** [comment]
Since the announce of Intel planning to remove legacy BIOS support by 2020, i opted for UEFI  in virtual machines when supported.

**Comment by Ricky-Tigg** [comment]
"_latest work in progress image here_" | Link is no more valid.

**Comment by fichtner** [comment]
Yes?! 😉

**Comment by fichtner** [comment]
217-RC1 images have been released 2 weeks ago and I haven't had any feedback on such issues from others. If it still isn't good I don't know what to do and research must be done within FreeBSD.

**Comment by Ricky-Tigg** [comment]
Then thanks to those that might be the _others_ you refereed to, you must be able to say on which platform the present issue has not been reproducible. As expected the issue remains reproducible on my system – Fedora 34 – in regards of this test-case while _OPNsense-21.7.r1-OpenSSL-dvd-amd64.iso_ is involved.

**Comment by fichtner** [comment]
Easy, just go to https://bugs.freebsd.org and open a report there about "bsdinstall".
